"""empty message

Revision ID: 53170455be65
Revises: e1ff22f33013
Create Date: 2022-06-01 16:51:23.103063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53170455be65'
down_revision = 'e1ff22f33013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'present')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('present', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
