"""empty message

Revision ID: 904f0b3e12ab
Revises: 037eab76b82c
Create Date: 2022-06-01 16:45:21.764816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '904f0b3e12ab'
down_revision = '037eab76b82c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('show_time', sa.String(length=120), nullable=False))
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('show', 'show_time')
    # ### end Alembic commands ###
