"""empty message

Revision ID: e1ff22f33013
Revises: 904f0b3e12ab
Create Date: 2022-06-01 16:49:55.368069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ff22f33013'
down_revision = '904f0b3e12ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.String(length=120), nullable=False))
    op.add_column('show', sa.Column('present', sa.String(length=120), nullable=False))
    op.drop_column('show', 'show_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('show_time', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('show', 'present')
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
